### ISSUE TITLE
Roadmap for `repair.py`

### ISSUE THREAD

**Issue by jmtsuji** [jmtsuji/rotary#26]
Tasks for `repair.py` after the MVP version is finished:
- [ ] Add option for pass-through of circular contigs that failed end repair, rather than exiting with error status
- [ ] Separate the contig rotation function into its own separate module
- [ ] Fine-tune the `circlator merge` parameters to better guarantee success of merging contigs
- [ ] If merge success is drastically improved after working on the `circlator merge` params, then the default number of `length_threshold` iterations in the script can probably be decreased to save run time on complex samples.
- [ ] Change how the `assembly_info.txt` file is used. Right now, only contigs in this file are analyzed. It would be better if the circular contigs in this file are treated as circular, but then all other contigs in the input FastA file are passed through the script as linear (rather than discarding contigs in the input FastA that aren't in `assembly_info.txt`). The code will need to be refactored a bit to handle this.

In the long term:
- [ ] Completely replace `circulator merge` with in-house scripts to handle stitching the end-spanning contig onto the ends of the circular contig
- [ ] Add a report that shows exactly how end-repaired contigs were changed (including modified bases and how the rotation point was adjusted relative to the old contig, anchored at a non-modified point). This will allow users to see if their dataset is actually being changed at all by end repair
- [ ] Consider adding support for some of the other edge cases that can be issues in circularization (mentioned in the `circlator` paper), although I wonder if modern assemblers already handle these cases by default: e.g., checking to ensure that short circular contigs don't contain multiple repeats of the real contig sequence due to assembly issues
